name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**/.gitignore"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**/.gitignore"
  workflow_dispatch:
    inputs:
      build-plugin:
        description: "Build audio-plugin"
        type: boolean
        default: true
      build-console:
        description: "Build console-app"
        type: boolean
        default: false
      build-gui:
        description: "Build gui-app"
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-examples-macos:
    name: Build Examples (macOS)
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-macos.10.15, aarch64-macos.11.0]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31.8.4

      - name: Build audio-plugin
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.build-plugin == 'true' }}
        run: nix develop -c zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast --summary all
        working-directory: examples/audio-plugin

      - name: Build console-app
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.build-console == 'true' }}
        run: nix develop -c zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast --summary all
        working-directory: examples/console-app

      - name: Build gui-app
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.build-gui == 'true' }}
        run: nix develop -c zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast --summary all
        working-directory: examples/gui-app

  build-examples-linux:
    name: Build Examples (Linux)
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Nix
        uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31.8.4

      - name: Build audio-plugin
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.build-plugin == 'true' }}
        run: nix develop -c zig build -Doptimize=ReleaseFast --summary all
        working-directory: examples/audio-plugin

      - name: Build console-app
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.build-console == 'true' }}
        run: nix develop -c zig build -Doptimize=ReleaseFast --summary all
        working-directory: examples/console-app

      - name: Build gui-app
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.build-gui == 'true' }}
        run: nix develop -c zig build -Doptimize=ReleaseFast --summary all
        working-directory: examples/gui-app

